[project]
name = "sharkadm-zip-creator"
version = "0.1.0"
description = "Flet GUI for creating zip packages for SHARK"
authors = [
    {name = "Magnus Wenzer", email = "magnus.wenzer@smhi.se"},
]
dependencies = [
    "flet>=0.24.1",
    "flet-desktop>=0.85.3",
    "polars==1.31.0",
    "screeninfo>=0.8.1",
    "sharkadm @ git+https://github.com/nodc-sweden/SHARKadm.git@v4.1.0",
    "nodc-station @ git+https://github.com/nodc-sweden/nodc-station.git@v2.1.0",
    "nodc-codes @ git+https://github.com/nodc-sweden/nodc-codes.git@v3.0.0",
    "nodc-worms @ git+https://github.com/nodc-sweden/nodc-worms.git@v1.0.0",
    "nodc-bvol @ git+https://github.com/nodc-sweden/nodc-bvol.git@v0.2.0",
    "nodc-occurrence-id @ git+https://github.com/nodc-sweden/nodc-occurrence-id.git@v0.1.0",
    "nodc-geography @ git+https://github.com/nodc-sweden/nodc-geography.git@v2.0.1",
    "nodc-dyntaxa @ git+https://github.com/nodc-sweden/nodc-dyntaxa.git@v0.2.0",
]
requires-python = ">=3.11, <3.13"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.13.1",
    "pre-commit>=4.3.0",
    "freezegun>=1.5.4",
]

[tool.ruff]
line-length = 90
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = [
    "A",  # flake8-builtins
    "F",  # pyflakes
    "E", # pycodestyle: error
    "W",  # pycodestyle: warning
    "I",  # isort: unsorted-imports
    "RUF"  # Ruff-specific rules
]

per-file-ignores."__init__.py" = ["F401"]

[tool.hatch.metadata]
allow-direct-references = true

#[tool.uv.sources]
#sharkadm = { git = "https://github.com/nodc-sweden/SHARKadm.git", rev = "v4.1.0" }
#nodc-station = { git = "https://github.com/nodc-sweden/nodc-station.git", rev = "v2.1.0" }
#nodc-codes = { git = "https://github.com/nodc-sweden/nodc-codes.git", rev = "v3.0.0" }
#nodc-bvol = { git = "https://github.com/nodc-sweden/nodc-bvol.git", rev = "v0.2.0" }
#nodc-worms = { git = "https://github.com/nodc-sweden/nodc-worms.git", rev = "v1.0.0" }
#nodc-occurrence-id = { git = "https://github.com/nodc-sweden/nodc-occurrence-id.git", rev = "v0.1.0" }
#nodc-geography = { git = "https://github.com/nodc-sweden/nodc-geography.git", rev = "v2.0.1" }
#nodc-dyntaxa = { git = "https://github.com/nodc-sweden/nodc-dyntaxa.git", rev = "v0.2.0" }



